name: WebAssembly Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: latest
        
    - name: Configure CMake for WASM
      run: |
        mkdir build-wasm
        cd build-wasm
        emcmake cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=OFF \
          -DCMAKE_EXECUTABLE_SUFFIX=".js"
          
    - name: Build WASM
      run: |
        cd build-wasm
        emmake make
        
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flowgraph-wasm
        path: |
          build-wasm/*.wasm
          build-wasm/*.js
          build-wasm/*.html
