name: WebAssembly Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Enable debug build'
        required: false
        default: false
        type: boolean
      optimization_level:
        description: 'Emscripten optimization level'
        required: false
        default: '3'
        type: choice
        options:
          - '0'
          - '1'
          - '2'
          - '3'
      enable_threads:
        description: 'Enable WASM threads'
        required: false
        default: true
        type: boolean

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: latest
        
    - name: Configure CMake for WASM
      run: |
        mkdir build-wasm
        cd build-wasm
        emcmake cmake .. \
          -DCMAKE_BUILD_TYPE=${{ inputs.debug_enabled && 'Debug' || 'Release' }} \
          -DBUILD_TESTING=OFF \
          -DCMAKE_EXECUTABLE_SUFFIX=".js" \
          -DOPTIMIZATION_LEVEL=${{ inputs.optimization_level || '3' }} \
          -DENABLE_THREADS=${{ inputs.enable_threads || true }}
          
    - name: Build WASM
      run: |
        cd build-wasm
        emmake make
        
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flowgraph-wasm
        path: |
          build-wasm/*.wasm
          build-wasm/*.js
          build-wasm/*.html
        
    - name: Upload debug symbols
      if: inputs.debug_enabled
      uses: actions/upload-artifact@v3
      with:
        name: flowgraph-wasm-debug
        path: |
          build-wasm/*.wasm.map
          build-wasm/*.js.map
